<div class="row g-4 determinant-calc-rebuilt">
    <div class="col-lg-12">
        <div class="calculator-card">
            
            <div class="calculator-body">
                <div class="mb-4">
                    <label class="form-label-custom">Matrix Size</label>
                    <div class="d-flex gap-2">
                        <button class="btn btn-outline-teal active flex-grow-1" data-size="2">2x2</button>
                        <button class="btn btn-outline-teal flex-grow-1" data-size="3">3x3</button>
                        <button class="btn btn-outline-teal flex-grow-1" data-size="4">4x4</button>
                        <button class="btn btn-outline-teal flex-grow-1" data-size="5">5x5</button>
                    </div>
                </div>

                <div id="matrix-input-grid" class="d-flex flex-column gap-2 mb-4 align-items-center">
                    <!-- Grid generated by JS -->
                </div>

                <div class="row g-3">
                    <div class="col-md-12">
                        <label class="form-label-custom">Actions</label>
                        <div class="d-flex gap-2">
                            <button class="btn btn-outline-danger w-100 rounded-3" id="clear-matrix" style="min-width: 280px; max-width: 100%;"><i class="fas fa-eraser me-2"></i>Clear</button>
                            <button class="btn btn-outline-secondary w-100 rounded-3" id="random-matrix" style="min-width: 280px; max-width: 100%;"><i class="fas fa-dice me-2"></i>Random</button>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label-custom">Precision</label>
                        <select id="precision-sel" class="form-select form-select-lg rounded-3">
                            <option value="0">Integers</option>
                            <option value="2">2 Decimals</option>
                            <option value="4">4 Decimals</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="output-card-themed" style="--tool-hue:170;--tool-color:#0d9488;--tool-bg:rgba(20,184,166,.04);">
            <div class="output-hero">
                <span class="output-hero-label">Determinant |A|</span>
                <div class="output-hero-value" id="out-det">0</div>
            </div>

            <div class="mt-4">
                <h6 class="fw-bold mb-3"><i class="fas fa-layer-group me-2 text-primary"></i>Solution steps (Cofactor Expansion)</h6>
                <div class="bg-white p-4 rounded-4 border shadow-sm small text-secondary overflow-auto" id="math-steps">
                    Enter values to see steps.
                </div>
            </div>

            <div class="row g-2 mt-4">
                <div class="col-md-12">
                    <button class="btn d-block mx-auto btn-dark py-3 px-5 fw-bold rounded-pill shadow-sm" id="copy-solution" style="min-width: 280px; max-width: 100%;"><i class="fas fa-copy me-2"></i>Copy Solution</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const $ = id => document.getElementById(id);
    let matrixSize = 2;

    function createGrid(size) {
        matrixSize = size;
        const grid = $('matrix-input-grid');
        grid.innerHTML = '';
        for (let i = 0; i < size; i++) {
            const row = document.createElement('div');
            row.className = 'd-flex gap-2';
            for (let j = 0; j < size; j++) {
                const input = document.createElement('input');
                input.type = 'number';
                input.className = 'form-control matrix-cell text-center';
                input.value = '0';
                input.dataset.row = i;
                input.dataset.col = j;
                input.style.width = '60px';
                input.style.height = '60px';
                input.addEventListener('input', calculate);
                row.appendChild(input);
            }
            grid.appendChild(row);
        }
        calculate();
    }

    function getMatrix() {
        const matrix = [];
        for (let i = 0; i < matrixSize; i++) {
            matrix[i] = [];
            for (let j = 0; j < matrixSize; j++) {
                const el = document.querySelector(`.matrix-cell[data-row="${i}"][data-col="${j}"]`);
                matrix[i][j] = parseFloat(el.value) || 0;
            }
        }
        return matrix;
    }

    function getDeterminant(m) {
        if (m.length === 1) return m[0][0];
        if (m.length === 2) return (m[0][0] * m[1][1]) - (m[0][1] * m[1][0]);
        
        let det = 0;
        for (let i = 0; i < m[0].length; i++) {
            det += Math.pow(-1, i) * m[0][i] * getDeterminant(m.slice(1).map(row => row.filter((_, j) => j !== i)));
        }
        return det;
    }

    function calculate() {
        const m = getMatrix();
        const det = getDeterminant(m);
        const p = parseInt($('precision-sel').value);
        $('out-det').textContent = det.toFixed(p);

        let steps = [];
        if (matrixSize === 2) {
            steps.push(`For a 2x2 matrix [[a, b], [c, d]]:`);
            steps.push(`det = ad - bc`);
            steps.push(`det = (${m[0][0]} × ${m[1][1]}) - (${m[0][1]} × ${m[1][0]})`);
            steps.push(`det = ${m[0][0]*m[1][1]} - ${m[0][1]*m[1][0]}`);
            steps.push(`<strong>det = ${det.toFixed(p)}</strong>`);
        } else if (matrixSize === 3) {
            steps.push(`Expansion along first row:`);
            for (let j = 0; j < 3; j++) {
                const sign = Math.pow(-1, j) > 0 ? '+' : '-';
                const sub = m.slice(1).map(row => row.filter((_, colIdx) => colIdx !== j));
                const subDet = (sub[0][0] * sub[1][1]) - (sub[0][1] * sub[1][0]);
                steps.push(`${sign} (${m[0][j]}) × |[${sub[0][0]}, ${sub[0][1]}], [${sub[1][0]}, ${sub[1][1]}]|`);
                steps.push(`&nbsp;&nbsp;&nbsp; = ${sign} (${m[0][j]}) × (${subDet}) = ${ (Math.pow(-1, j) * m[0][j] * subDet).toFixed(p) }`);
            }
            steps.push(`<br>Total Determinant = <strong>${det.toFixed(p)}</strong>`);
        } else {
            steps.push(`Determinant calculated via recursive cofactor expansion.`);
            steps.push(`Final Result = <strong>${det.toFixed(p)}</strong>`);
        }
        $('math-steps').innerHTML = steps.join('<br>');
    }

    document.querySelectorAll('[data-size]').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('[data-size]').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            createGrid(parseInt(btn.dataset.size));
        });
    });

    $('clear-matrix').addEventListener('click', () => {
        document.querySelectorAll('.matrix-cell').forEach(c => c.value = '0');
        calculate();
    });

    $('random-matrix').addEventListener('click', () => {
        document.querySelectorAll('.matrix-cell').forEach(c => c.value = Math.floor(Math.random() * 20) - 10);
        calculate();
    });

    $('precision-sel').addEventListener('change', calculate);

    $('copy-solution').addEventListener('click', function() {
        const text = `Matrix Determinant (${matrixSize}x${matrixSize})\nResult: ${$('out-det').textContent}\nGenerated by ToolsHub`;
        navigator.clipboard.writeText(text).then(() => {
            const o = this.innerHTML;
            this.innerHTML = '<i class="fas fa-check me-2"></i>Copied!';
            setTimeout(() => this.innerHTML = o, 2000);
        });
    });

    createGrid(2);
});
</script>

<style>
.determinant-calc-rebuilt .calculator-card { background: #fff; border: 1px solid #e5e7eb; border-radius: 20px; padding: 2rem; box-shadow: 0 4px 24px rgba(0,0,0,.04); }
.determinant-calc-rebuilt .calculator-header { display: flex; align-items: center; gap: 1rem; margin-bottom: 2rem; }
.determinant-calc-rebuilt .calculator-header h4 { margin: 0; font-weight: 800; color: #1e293b; }
.determinant-calc-rebuilt .calculator-header p { margin: 0; font-size: .9rem; color: #64748b; }
.determinant-calc-rebuilt .tool-icon-circle { width: 56px; height: 56px; border-radius: 14px; display: flex; align-items: center; justify-content: center; font-size: 1.4rem; flex-shrink: 0; }
.determinant-calc-rebuilt .form-label-custom { font-size: .8rem; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: .5px; margin-bottom: .4rem; display: block; }
.btn-outline-teal { border: 1.5px solid #ccfbf1; color: #0d9488; font-weight: 600; border-radius: 12px; transition: all 0.2s; }
.btn-outline-teal:hover, .btn-outline-teal.active { background: #14b8a6; color: #fff; border-color: #14b8a6; box-shadow: 0 4px 12px rgba(20,184,166,.2); }
.matrix-cell { font-weight: bold; font-size: 1.1rem; border-radius: 10px !important; border: 2px solid #f1f5f9; transition: all 0.2s; }
.matrix-cell:focus { border-color: #14b8a6; box-shadow: none; background: #f0fdfa; }

.features-grid { grid-template-columns: 1fr !important; }
.features-grid > div { margin-bottom: 1rem; }
</style>

