<div class="tool-interactive-container">
    <div class="card border-0 shadow-sm p-4 mb-4 bg-white rounded-4">
        <div class="row g-3 align-items-end mb-4">
            <div class="col-md-3"><label class="form-label fw-bold small text-uppercase text-muted">Art Style</label><select id="gen-style" class="form-select border-2"><option value="any">Any Style</option><option value="realistic">Realistic</option><option value="anime">Anime/Manga</option><option value="abstract">Abstract</option><option value="cartoon">Cartoon</option><option value="sketch">Pencil Sketch</option></select></div>
            <div class="col-md-3"><label class="form-label fw-bold small text-uppercase text-muted">Difficulty</label><select id="gen-diff" class="form-select border-2"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></div>
            <div class="col-md-3"><label class="form-label fw-bold small text-uppercase text-muted">Subject</label><select id="gen-subject" class="form-select border-2"><option value="character">Character</option><option value="landscape">Landscape</option><option value="animal">Animal</option><option value="object">Object</option><option value="fantasy">Fantasy</option></select></div>
            <div class="col-md-3"><button id="gen-btn" class="btn btn-accent px-4 py-2 w-100 fw-bold rounded-3"><i class="fas fa-palette me-2"></i>Generate</button></div>
        </div>
        <div id="gen-results" class="d-none"><h5 class="fw-bold mb-3"><i class="fas fa-palette me-2 text-warning"></i>Drawing Prompts</h5><div id="gen-list" class="list-group gap-2"></div></div>
        <div id="gen-placeholder" class="text-center py-5"><div class="opacity-25 mb-3"><i class="fas fa-palette fa-4x"></i></div><h5 class="text-muted">Choose your preferences to get drawing prompts</h5></div>
    </div>
</div>
<style>.btn-accent{background:linear-gradient(135deg,#f093fb,#f5576c);color:#fff;border:none;transition:.3s}.btn-accent:hover{transform:translateY(-1px);opacity:.9;color:#fff}.list-group-item-action{border-radius:12px!important;border:2px solid #f8f9fa!important;transition:.2s;cursor:pointer}.list-group-item-action:hover{border-color:#f5576c!important;background:#fff5f7}.copy-icon{opacity:0;transition:.2s}.list-group-item-action:hover .copy-icon{opacity:1}</style>
<script>
document.addEventListener('DOMContentLoaded',function(){const btn=document.getElementById('gen-btn'),style=document.getElementById('gen-style'),diff=document.getElementById('gen-diff'),subject=document.getElementById('gen-subject'),results=document.getElementById('gen-results'),list=document.getElementById('gen-list'),ph=document.getElementById('gen-placeholder');btn.addEventListener('click',function(){btn.disabled=true;btn.innerHTML='<i class="fas fa-spinner fa-spin me-2"></i>Generating...';fetch('{{ route("ai.generate",["type"=>"drawing-prompt"]) }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({style:style.value,difficulty:diff.value,subject:subject.value})}).then(r=>r.json()).then(data=>{if(data.success){ph.classList.add('d-none');results.classList.remove('d-none');list.innerHTML='';data.results.forEach(item=>{const d=document.createElement('div');d.className='list-group-item list-group-item-action p-3 mb-2';d.innerHTML=`<div class="d-flex justify-content-between align-items-center"><span class="fw-medium">${item}</span><i class="fas fa-copy text-danger copy-icon"></i></div>`;d.addEventListener('click',()=>{navigator.clipboard.writeText(item).then(()=>{const o=d.innerHTML;d.innerHTML='<span class="text-success fw-bold"><i class="fas fa-check me-2"></i>Copied!</span>';setTimeout(()=>d.innerHTML=o,2e3);});});list.appendChild(d);});}}).finally(()=>{btn.disabled=false;btn.innerHTML='<i class="fas fa-palette me-2"></i>Generate';});});});
</script>
