<div class="interactive-tool-container">
    {{-- ════════════ INPUT SECTION ════════════ --}}
    <div class="card border-0 shadow-sm rounded-4 mb-4">
        <div class="card-body p-4 p-md-5">
            <h4 class="fw-bold text-dark mb-4"><i class="fas fa-clover text-accent me-2"></i> Fortune Profile</h4>
            <p class="text-secondary small mb-4">Enter your details to find your synchronized lucky numbers based on numerological principles.</p>
            
            <div class="row g-4">
                <div class="col-12 col-md-6">
                    <label class="form-label fw-semibold text-uppercase small letter-spacing-1 text-muted">Your Name</label>
                    <div class="input-group input-group-lg shadow-sm rounded-3 overflow-hidden border">
                        <span class="input-group-text bg-white border-0"><i class="fas fa-user-tag text-accent"></i></span>
                        <input type="text" id="lucky-num-name-input" class="form-control border-0 px-3" placeholder="e.g. Sage">
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <label class="form-label fw-semibold text-uppercase small letter-spacing-1 text-muted">Birth Date</label>
                    <div class="input-group input-group-lg shadow-sm rounded-3 overflow-hidden border">
                        <span class="input-group-text bg-white border-0"><i class="fas fa-calendar-alt text-accent"></i></span>
                        <input type="date" id="lucky-num-dob-input" class="form-control border-0 px-3" value="1990-01-01">
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- ════════════ ACTION BAR ════════════ --}}
    <div class="text-center mb-5">
        <button id="lucky-num-btn-find" class="btn btn-accent btn-lg px-5 py-3 fw-bold shadow-sm rounded-pill transition-all">
            <i class="fas fa-dice me-2"></i> Generate Lucky Numbers
        </button>
    </div>

    {{-- ════════════ RESULT SECTION ════════════ --}}
    <div id="lucky-num-result-card" class="card border-0 shadow-lg rounded-4 d-none">
        <div class="card-body p-4 p-md-5 text-center">
            <div class="d-flex justify-content-between align-items-center mb-5 pb-3 border-bottom text-start">
                <h4 class="fw-bold text-dark mb-0"><i class="fas fa-star text-accent me-2"></i> Your Lucky Numbers</h4>
                <button class="btn btn-sm btn-outline-accent rounded-pill px-3" id="lucky-num-btn-copy">
                    <i class="fas fa-copy me-1"></i> Copy
                </button>
            </div>

            <div class="row g-4 mb-5 justify-content-center">
                {{-- Master Lucky Number --}}
                <div class="col-12 mb-2">
                    <div class="p-4 rounded-4 bg-light border">
                        <h6 class="text-uppercase small fw-bold text-muted mb-3">Primary Destiny Number</h6>
                        <div id="lucky-num-res-primary" class="display-3 fw-black text-accent">-</div>
                    </div>
                </div>
                
                {{-- Secondary Numbers --}}
                <div class="col-6 col-md-3">
                    <div class="p-3 rounded-4 bg-white border h-100 shadow-sm">
                        <div class="small text-muted mb-1">Daily Luck</div>
                        <div id="lucky-num-res-daily" class="h2 fw-black text-dark">-</div>
                    </div>
                </div>
                <div class="col-6 col-md-3">
                    <div class="p-3 rounded-4 bg-white border h-100 shadow-sm">
                        <div class="small text-muted mb-1">Spirit</div>
                        <div id="lucky-num-res-spirit" class="h2 fw-black text-dark">-</div>
                    </div>
                </div>
                <div class="col-6 col-md-3">
                    <div class="p-3 rounded-4 bg-white border h-100 shadow-sm">
                        <div class="small text-muted mb-1">Success</div>
                        <div id="lucky-num-res-success" class="h2 fw-black text-dark">-</div>
                    </div>
                </div>
                <div class="col-6 col-md-3">
                    <div class="p-3 rounded-4 bg-white border h-100 shadow-sm">
                        <div class="small text-muted mb-1">Fortune</div>
                        <div id="lucky-num-res-fortune" class="h2 fw-black text-dark">-</div>
                    </div>
                </div>
            </div>

            <div class="p-4 rounded-4 bg-dark text-white shadow-inner text-start">
                <h6 class="fw-bold text-accent mb-2 small text-uppercase">Synchronicity Note</h6>
                <p class="mb-0 small" style="opacity: 0.8; line-height: 1.6;">
                    These numbers are generated by aligning your name vibration with your birth data and the current planetary cycles. Use them as focal points for meditation or intention setting.
                </p>
            </div>
        </div>
    </div>
</div>

<style>
    .interactive-tool-container { --lucky-accent: #ff6b00; }
    .interactive-tool-container .text-accent { color: var(--lucky-accent) !important; }
    .interactive-tool-container .btn-accent { background: var(--lucky-accent); color: white; border: none; }
    .interactive-tool-container .btn-accent:hover { background: #e65100; color: white; transform: translateY(-2px); }
    .interactive-tool-container .btn-outline-accent { color: var(--lucky-accent); border-color: var(--lucky-accent); }
    .interactive-tool-container .btn-outline-accent:hover { background: var(--lucky-accent); color: white; }
    .interactive-tool-container .fw-black { font-weight: 900; }
    .interactive-tool-container .letter-spacing-1 { letter-spacing: 1px; }
    .interactive-tool-container .transition-all { transition: all 0.3s ease; }
    .interactive-tool-container .shadow-inner { box-shadow: inset 0 2px 10px rgba(0,0,0,0.1); }
</style>

<script>
(function() {
    function initLuckyNumberFinder() {
        const btnFind = document.getElementById('lucky-num-btn-find');
        const resultCard = document.getElementById('lucky-num-result-card');

        if (!btnFind || !resultCard) return;

        function reduce(num) {
            if (num <= 9) return num;
            const sum = num.toString().split('').reduce((a, b) => a + parseInt(b), 0);
            return reduce(sum);
        }

        btnFind.addEventListener('click', function() {
            const nameInput = document.getElementById('lucky-num-name-input');
            const dobInput = document.getElementById('lucky-num-dob-input');
            
            const name = nameInput.value.trim();
            const dob = dobInput.value;

            if (!name || !dob) {
                alert('Please provide your name and birth date.');
                return;
            }

            btnFind.innerHTML = '<i class="fas fa-circle-notch fa-spin me-2"></i> Aligning Frequencies...';
            btnFind.disabled = true;

            setTimeout(() => {
                // Life Path Number
                const dobDigits = dob.replace(/-/g, '');
                const lifePath = reduce(dobDigits.split('').reduce((a, b) => a + parseInt(b), 0));

                // Name Number
                const nameSum = name.toLowerCase().split('').reduce((a, b) => {
                    const code = b.charCodeAt(0) - 96;
                    return a + (code > 0 && code <= 26 ? reduce(code) : 0);
                }, 0);
                const nameNum = reduce(nameSum);

                // Seed based on current date
                const now = new Date();
                const dailySeed = now.getDate() + now.getMonth() + now.getFullYear();

                document.getElementById('lucky-num-res-primary').textContent = reduce(lifePath + nameNum);
                document.getElementById('lucky-num-res-daily').textContent = (dailySeed + nameNum) % 99 + 1;
                document.getElementById('lucky-num-res-spirit').textContent = (lifePath * 7) % 9 + 1;
                document.getElementById('lucky-num-res-success').textContent = (nameNum * 3 + lifePath) % 21 + 1;
                document.getElementById('lucky-num-res-fortune').textContent = (dailySeed * lifePath) % 77 + 1;

                resultCard.classList.remove('d-none');
                resultCard.scrollIntoView({ behavior: 'smooth', block: 'center' });

                btnFind.innerHTML = '<i class="fas fa-dice me-2"></i> Generate Lucky Numbers';
                btnFind.disabled = false;
            }, 800);
        });

        const btnCopy = document.getElementById('lucky-num-btn-copy');
        if (btnCopy) {
            btnCopy.addEventListener('click', function() {
                const primary = document.getElementById('lucky-num-res-primary').innerText;
                const daily = document.getElementById('lucky-num-res-daily').innerText;
                const spirit = document.getElementById('lucky-num-res-spirit').innerText;
                const success = document.getElementById('lucky-num-res-success').innerText;
                const fortune = document.getElementById('lucky-num-res-fortune').innerText;
                
                const text = `My Lucky Numbers:\nPrimary: ${primary}\nDaily Luck: ${daily}\nSpirit: ${spirit}\nSuccess: ${success}\nFortune: ${fortune}`;
                
                navigator.clipboard.writeText(text).then(() => {
                    const original = this.innerHTML;
                    this.innerHTML = '<i class="fas fa-check me-1"></i> Copied!';
                    setTimeout(() => this.innerHTML = original, 2000);
                });
            });
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initLuckyNumberFinder);
    } else {
        initLuckyNumberFinder();
    }
})();
</script>
