<div class="row g-4 passive-income-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">Dividend Income ($/yr)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="pi-div" class="form-control form-control-lg" value="6000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Rental Income ($/yr)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="pi-rent" class="form-control form-control-lg" value="12000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Interest Income ($/yr)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="pi-int" class="form-control form-control-lg" value="2000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Royalties/Other ($/yr)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="pi-royal" class="form-control form-control-lg" value="1000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Annual Expenses ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="pi-exp" class="form-control form-control-lg" value="3000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Tax Rate (%)</label><div class="input-group"><input type="number" id="pi-tax" class="form-control form-control-lg" value="25" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:140;--tool-color:#22c55e;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Passive Income Calculator</span><div class="output-hero-value" id="passive-val">—</div><span class="output-hero-unit" id="passive-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">GROSS INCOME</span><span class="stat-card-value" style="color:#22c55e" id="pi-gross">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">NET INCOME</span><span class="stat-card-value" style="color:#3b82f6" id="pi-net">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#f59e0b;background:rgba(0,0,0,.02);"><span class="stat-card-label">MONTHLY</span><span class="stat-card-value" style="color:#f59e0b" id="pi-monthly">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#a855f7;background:rgba(0,0,0,.02);"><span class="stat-card-label">FIRE RATIO</span><span class="stat-card-value" style="color:#a855f7" id="pi-fire">—</span></div></div></div><div class="mt-4" id="passive-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="passive-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="passive-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="passive-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const d=parseFloat($('pi-div').value)||0,r=parseFloat($('pi-rent').value)||0,i=parseFloat($('pi-int').value)||0,ro=parseFloat($('pi-royal').value)||0,e=parseFloat($('pi-exp').value)||0,t=(parseFloat($('pi-tax').value)||0)/100;
const gross=d+r+i+ro,net=(gross-e)*(1-t),monthly=net/12,fire=e>0?(gross/(e*12)*100):0;
$('passive-val').textContent=fmt(net)+'/yr';$('pi-gross').textContent=fmt(gross);$('pi-net').textContent=fmt(net);$('pi-monthly').textContent=fmt(monthly)+'/mo';$('pi-fire').textContent=fire.toFixed(0)+'%';
$('passive-st').textContent=net>50000?'FINANCIAL FREEDOM':net>20000?'GROWING':'BUILDING';$('passive-st').style.color=net>50000?'#22c55e':net>20000?'#f59e0b':'#64748b';
let ins=[];ins.push('Gross passive income: <strong>'+fmt(gross)+'/yr</strong>. After tax & expenses: <strong>'+fmt(net)+'/yr</strong>.');
ins.push('Monthly passive income: <strong>'+fmt(monthly)+'</strong>.');
$('passive-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['pi-div','pi-rent','pi-int','pi-royal','pi-exp','pi-tax'].forEach(id=>$(id).addEventListener('input',calc));
$('passive-cb').addEventListener('click',calc);
$('passive-cp').addEventListener('click',function(){navigator.clipboard.writeText('Passive Income Calculator: '+$('passive-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('passive-rs').addEventListener('click',()=>{$('pi-div').value=6000;$('pi-rent').value=12000;$('pi-int').value=2000;$('pi-royal').value=1000;$('pi-exp').value=3000;$('pi-tax').value=25;calc();});calc();});
</script>
<style>.passive-income-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.passive-income-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.passive-income-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.passive-income-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.passive-income-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.passive-income-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style>