<div class="row g-4 relocation-expense-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">Moving Costs ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="rel-move" class="form-control form-control-lg" value="5000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Housing Deposit ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="rel-house" class="form-control form-control-lg" value="3000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Travel Costs ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="rel-travel" class="form-control form-control-lg" value="1500" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Temp Housing ($/mo)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="rel-temp" class="form-control form-control-lg" value="2000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Temp Months</label><div class="input-group"><input type="number" id="rel-months" class="form-control form-control-lg" value="2" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Miscellaneous ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="rel-misc" class="form-control form-control-lg" value="1000" min="0"></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:25;--tool-color:#f97316;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Relocation Expense Calculator</span><div class="output-hero-value" id="relocation-val">—</div><span class="output-hero-unit" id="relocation-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#f97316;background:rgba(0,0,0,.02);"><span class="stat-card-label">TOTAL COST</span><span class="stat-card-value" style="color:#f97316" id="rel-total">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">TEMP HOUSING</span><span class="stat-card-value" style="color:#3b82f6" id="rel-temp-t">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">FIXED COSTS</span><span class="stat-card-value" style="color:#22c55e" id="rel-fixed">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#a855f7;background:rgba(0,0,0,.02);"><span class="stat-card-label">DAILY RATE</span><span class="stat-card-value" style="color:#a855f7" id="rel-daily">—</span></div></div></div><div class="mt-4" id="relocation-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="relocation-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="relocation-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="relocation-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const mv=parseFloat($('rel-move').value)||0,h=parseFloat($('rel-house').value)||0,tr=parseFloat($('rel-travel').value)||0,tmp=parseFloat($('rel-temp').value)||0,mo=parseFloat($('rel-months').value)||0,misc=parseFloat($('rel-misc').value)||0;
const tempTotal=tmp*mo,fixed=mv+h+tr+misc,total=fixed+tempTotal,daily=mo>0?total/(mo*30):0;
$('relocation-val').textContent=fmt(total);$('rel-total').textContent=fmt(total);$('rel-temp-t').textContent=fmt(tempTotal);$('rel-fixed').textContent=fmt(fixed);$('rel-daily').textContent=fmt(daily)+'/day';
$('relocation-st').textContent='TOTAL BUDGET';$('relocation-st').style.color='#f97316';
let ins=[];ins.push('Total relocation budget: <strong>'+fmt(total)+'</strong>.');ins.push('Fixed costs: '+fmt(fixed)+'. Temporary housing: '+fmt(tempTotal)+' ('+mo+' months).');
$('relocation-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['rel-move','rel-house','rel-travel','rel-temp','rel-months','rel-misc'].forEach(id=>$(id).addEventListener('input',calc));
$('relocation-cb').addEventListener('click',calc);
$('relocation-cp').addEventListener('click',function(){navigator.clipboard.writeText('Relocation Expense Calculator: '+$('relocation-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('relocation-rs').addEventListener('click',()=>{$('rel-move').value=5000;$('rel-house').value=3000;$('rel-travel').value=1500;$('rel-temp').value=2000;$('rel-months').value=2;$('rel-misc').value=1000;calc();});calc();});
</script>
<style>.relocation-expense-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.relocation-expense-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.relocation-expense-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.relocation-expense-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.relocation-expense-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.relocation-expense-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style>