<div class="row g-4 rule-of-72-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-4"><label class="form-label-custom">Interest Rate (%)</label><div class="input-group"><input type="number" id="r72-rate" class="form-control form-control-lg" value="8" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-4"><label class="form-label-custom">Inflation Rate (%)</label><div class="input-group"><input type="number" id="r72-inf" class="form-control form-control-lg" value="3" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-4"><label class="form-label-custom">Initial Investment ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="r72-init" class="form-control form-control-lg" value="10000" min="0"></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:200;--tool-color:#0ea5e9;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Rule of 72 Calculator</span><div class="output-hero-value" id="rule-val">—</div><span class="output-hero-unit" id="rule-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#0ea5e9;background:rgba(0,0,0,.02);"><span class="stat-card-label">DOUBLING TIME</span><span class="stat-card-value" style="color:#0ea5e9" id="r72-dbl">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">EXACT (LOG)</span><span class="stat-card-value" style="color:#3b82f6" id="r72-exact">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#f59e0b;background:rgba(0,0,0,.02);"><span class="stat-card-label">REAL (ADJ)</span><span class="stat-card-value" style="color:#f59e0b" id="r72-real">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#a855f7;background:rgba(0,0,0,.02);"><span class="stat-card-label">QUADRUPLING</span><span class="stat-card-value" style="color:#a855f7" id="r72-quad">—</span></div></div></div><div class="mt-4" id="rule-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="rule-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="rule-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="rule-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const r=parseFloat($('r72-rate').value)||0,inf=parseFloat($('r72-inf').value)||0,init=parseFloat($('r72-init').value)||0;
if(r<=0){$('rule-val').textContent='∞';return;}const d=72/r,exact=Math.log(2)/Math.log(1+r/100),real=r-inf>0?72/(r-inf):Infinity,quad=exact*2;
$('rule-val').textContent=d.toFixed(1)+' yrs';$('r72-dbl').textContent=d.toFixed(1)+' yrs';$('r72-exact').textContent=exact.toFixed(2)+' yrs';$('r72-real').textContent=real===Infinity?'∞':real.toFixed(1)+' yrs';$('r72-quad').textContent=quad.toFixed(1)+' yrs';
$('rule-st').textContent=d<10?'FAST GROWTH':'STEADY GROWTH';$('rule-st').style.color=d<10?'#22c55e':'#f59e0b';
let ins=[];ins.push('At '+r+'%, money doubles every <strong>'+d.toFixed(1)+' years</strong> (exact: '+exact.toFixed(2)+').');
ins.push('After inflation ('+inf+'%), real doubling takes <strong>'+(real===Infinity?'∞':real.toFixed(1))+' years</strong>.');
if(init>0)ins.push('Your '+fmt(init)+' becomes <strong>'+fmt(init*2)+'</strong> in ~'+d.toFixed(0)+' years.');
$('rule-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['r72-rate','r72-inf','r72-init'].forEach(id=>$(id).addEventListener('input',calc));
$('rule-cb').addEventListener('click',calc);
$('rule-cp').addEventListener('click',function(){navigator.clipboard.writeText('Rule of 72 Calculator: '+$('rule-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('rule-rs').addEventListener('click',()=>{$('r72-rate').value=8;$('r72-inf').value=3;$('r72-init').value=10000;calc();});calc();});
</script>
<style>.rule-of-72-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.rule-of-72-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.rule-of-72-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.rule-of-72-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.rule-of-72-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.rule-of-72-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style>