<div class="row g-4 short-selling-profit-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">Entry Price ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="ss-sell" class="form-control form-control-lg" value="150" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Exit Price ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="ss-buy" class="form-control form-control-lg" value="120" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Shares</label><div class="input-group"><input type="number" id="ss-sh" class="form-control form-control-lg" value="100" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Borrow Fee (%)</label><div class="input-group"><input type="number" id="ss-fee" class="form-control form-control-lg" value="2" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">Days Held</label><div class="input-group"><input type="number" id="ss-days" class="form-control form-control-lg" value="30" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Dividends ($/Share)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="ss-div" class="form-control form-control-lg" value="0" min="0"></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:0;--tool-color:#ef4444;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Short Selling Profit Calculator</span><div class="output-hero-value" id="short-val">—</div><span class="output-hero-unit" id="short-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">GROSS PROFIT</span><span class="stat-card-value" style="color:#22c55e" id="ss-profit">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#ef4444;background:rgba(0,0,0,.02);"><span class="stat-card-label">TOTAL COSTS</span><span class="stat-card-value" style="color:#ef4444" id="ss-costs">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">NET PROFIT</span><span class="stat-card-value" style="color:#3b82f6" id="ss-net">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#a855f7;background:rgba(0,0,0,.02);"><span class="stat-card-label">ROI</span><span class="stat-card-value" style="color:#a855f7" id="ss-roi">—</span></div></div></div><div class="mt-4" id="short-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="short-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="short-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="short-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const sell=parseFloat($('ss-sell').value)||0,buy=parseFloat($('ss-buy').value)||0,sh=parseFloat($('ss-sh').value)||0,fee=(parseFloat($('ss-fee').value)||0)/100,days=parseFloat($('ss-days').value)||0,div=parseFloat($('ss-div').value)||0;
const gross=(sell-buy)*sh,borrowCost=sell*sh*fee*days/365,divCost=div*sh,totalCosts=borrowCost+divCost,net=gross-totalCosts,roi=sell*sh>0?(net/(sell*sh)*100):0;
$('short-val').textContent=fmt(net);$('ss-profit').textContent=fmt(gross);$('ss-costs').textContent=fmt(totalCosts);$('ss-net').textContent=fmt(net);$('ss-roi').textContent=roi.toFixed(2)+'%';
$('short-st').textContent=net>=0?'PROFITABLE SHORT':'SHORT LOSS';$('short-st').style.color=net>=0?'#22c55e':'#ef4444';
let ins=[];ins.push('Gross profit: <strong>'+fmt(gross)+'</strong>. Borrow cost: <strong>'+fmt(borrowCost)+'</strong>. Dividends owed: <strong>'+fmt(divCost)+'</strong>.');
ins.push('Net profit after costs: <strong>'+fmt(net)+'</strong> (ROI: '+roi.toFixed(1)+'%).');
$('short-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['ss-sell','ss-buy','ss-sh','ss-fee','ss-days','ss-div'].forEach(id=>$(id).addEventListener('input',calc));
$('short-cb').addEventListener('click',calc);
$('short-cp').addEventListener('click',function(){navigator.clipboard.writeText('Short Selling Profit Calculator: '+$('short-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('short-rs').addEventListener('click',()=>{$('ss-sell').value=150;$('ss-buy').value=120;$('ss-sh').value=100;$('ss-fee').value=2;$('ss-days').value=30;$('ss-div').value=0;calc();});calc();});
</script>
<style>.short-selling-profit-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.short-selling-profit-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.short-selling-profit-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.short-selling-profit-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.short-selling-profit-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.short-selling-profit-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style>