<div class="row g-4 import-duty-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">CIF Value ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="id-cif" class="form-control form-control-lg" value="10000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Duty Rate (%)</label><div class="input-group"><input type="number" id="id-duty" class="form-control form-control-lg" value="5" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">VAT/GST Rate (%)</label><div class="input-group"><input type="number" id="id-vat" class="form-control form-control-lg" value="10" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">Excise Duty (%)</label><div class="input-group"><input type="number" id="id-excise" class="form-control form-control-lg" value="0" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">Freight ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="id-freight" class="form-control form-control-lg" value="500" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Insurance ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="id-insurance" class="form-control form-control-lg" value="100" min="0"></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:190;--tool-color:#0891b2;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Import Duty Calculator</span><div class="output-hero-value" id="import-val">—</div><span class="output-hero-unit" id="import-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#0891b2;background:rgba(0,0,0,.02);"><span class="stat-card-label">DUTY AMOUNT</span><span class="stat-card-value" style="color:#0891b2" id="id-dutyamt">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">VAT/GST</span><span class="stat-card-value" style="color:#3b82f6" id="id-vatamt">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">LANDED COST</span><span class="stat-card-value" style="color:#22c55e" id="id-landed">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#f59e0b;background:rgba(0,0,0,.02);"><span class="stat-card-label">EFFECTIVE RATE</span><span class="stat-card-value" style="color:#f59e0b" id="id-eff">—</span></div></div></div><div class="mt-4" id="import-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="import-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="import-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="import-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const cif=parseFloat($('id-cif').value)||0,dr=(parseFloat($('id-duty').value)||0)/100,vr=(parseFloat($('id-vat').value)||0)/100,er=(parseFloat($('id-excise').value)||0)/100,fr=parseFloat($('id-freight').value)||0,ins=parseFloat($('id-insurance').value)||0;
const dutyAmt=cif*dr,excise=cif*er,taxBase=cif+dutyAmt+excise,vatAmt=taxBase*vr,totalDuties=dutyAmt+excise+vatAmt,landed=cif+totalDuties+fr+ins,effRate=cif>0?(totalDuties/cif*100):0;
$('import-val').textContent=fmt(totalDuties);$('id-dutyamt').textContent=fmt(dutyAmt);$('id-vatamt').textContent=fmt(vatAmt);$('id-landed').textContent=fmt(landed);$('id-eff').textContent=effRate.toFixed(1)+'%';
$('import-st').textContent='TOTAL DUTIES & TAXES';$('import-st').style.color='#0891b2';
let ins2=[];ins2.push('Customs duty: <strong>'+fmt(dutyAmt)+'</strong>. VAT/GST: <strong>'+fmt(vatAmt)+'</strong>.');ins2.push('Total landed cost: <strong>'+fmt(landed)+'</strong> (effective rate: '+effRate.toFixed(1)+'%).');
let insightList=ins2;
$('import-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+insightList.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['id-cif','id-duty','id-vat','id-excise','id-freight','id-insurance'].forEach(id=>$(id).addEventListener('input',calc));
$('import-cb').addEventListener('click',calc);
$('import-cp').addEventListener('click',function(){navigator.clipboard.writeText('Import Duty Calculator: '+$('import-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('import-rs').addEventListener('click',()=>{$('id-cif').value=10000;$('id-duty').value=5;$('id-vat').value=10;$('id-excise').value=0;$('id-freight').value=500;$('id-insurance').value=100;calc();});calc();});
</script>
<style>.import-duty-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.import-duty-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.import-duty-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.import-duty-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.import-duty-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.import-duty-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style><?php /**PATH D:\Xamp\htdocs\ToolsHub\resources\views\tools\interactive\import-duty-calculator.blade.php ENDPATH**/ ?>