<div class="row g-4 commercial-lease-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">Square Footage</label><div class="input-group"><input type="number" id="cl-sqft" class="form-control form-control-lg" value="2000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Rate ($/sqft/yr)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="cl-rate" class="form-control form-control-lg" value="25" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">CAM Charges ($/sqft/yr)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="cl-cam" class="form-control form-control-lg" value="8" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Annual Escalation (%)</label><div class="input-group"><input type="number" id="cl-esc" class="form-control form-control-lg" value="3" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">Lease Term (Years)</label><div class="input-group"><input type="number" id="cl-term" class="form-control form-control-lg" value="5" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Tenant Improvements ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="cl-ti" class="form-control form-control-lg" value="15000" min="0"></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:240;--tool-color:#6366f1;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Commercial Lease Calculator</span><div class="output-hero-value" id="commercial-val">—</div><span class="output-hero-unit" id="commercial-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#6366f1;background:rgba(0,0,0,.02);"><span class="stat-card-label">MONTHLY RENT</span><span class="stat-card-value" style="color:#6366f1" id="cl-monthly">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">ANNUAL COST</span><span class="stat-card-value" style="color:#3b82f6" id="cl-annual">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">TOTAL LEASE</span><span class="stat-card-value" style="color:#22c55e" id="cl-total">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#f59e0b;background:rgba(0,0,0,.02);"><span class="stat-card-label">EFFECTIVE RATE</span><span class="stat-card-value" style="color:#f59e0b" id="cl-eff">—</span></div></div></div><div class="mt-4" id="commercial-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="commercial-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="commercial-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="commercial-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const sqft=parseFloat($('cl-sqft').value)||0,rate=parseFloat($('cl-rate').value)||0,cam=parseFloat($('cl-cam').value)||0,esc=(parseFloat($('cl-esc').value)||0)/100,term=parseFloat($('cl-term').value)||1,ti=parseFloat($('cl-ti').value)||0;
const yr1=(rate+cam)*sqft,mo=yr1/12;let total=0;for(let y=0;y<term;y++)total+=(rate*Math.pow(1+esc,y)+cam)*sqft;total+=ti;const eff=total/(term*sqft);
$('commercial-val').textContent=fmt(mo)+'/mo';$('cl-monthly').textContent=fmt(mo);$('cl-annual').textContent=fmt(yr1);$('cl-total').textContent=fmt(total);$('cl-eff').textContent='\$'+eff.toFixed(2)+'/sqft';
$('commercial-st').textContent='LEASE ANALYSIS';$('commercial-st').style.color='#6366f1';
let ins=[];ins.push('Year 1 cost: <strong>'+fmt(yr1)+'</strong> ('+fmt(mo)+'/mo) for '+sqft+' sqft.');
ins.push('Total '+term+'-year lease cost: <strong>'+fmt(total)+'</strong> with '+esc*100+'% annual escalation.');
$('commercial-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['cl-sqft','cl-rate','cl-cam','cl-esc','cl-term','cl-ti'].forEach(id=>$(id).addEventListener('input',calc));
$('commercial-cb').addEventListener('click',calc);
$('commercial-cp').addEventListener('click',function(){navigator.clipboard.writeText('Commercial Lease Calculator: '+$('commercial-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('commercial-rs').addEventListener('click',()=>{$('cl-sqft').value=2000;$('cl-rate').value=25;$('cl-cam').value=8;$('cl-esc').value=3;$('cl-term').value=5;$('cl-ti').value=15000;calc();});calc();});
</script>
<style>.commercial-lease-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.commercial-lease-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.commercial-lease-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.commercial-lease-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.commercial-lease-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.commercial-lease-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style><?php /**PATH D:\Xamp\htdocs\ToolsHub\resources\views\tools\interactive\commercial-lease-calculator.blade.php ENDPATH**/ ?>