<div class="row g-4 eigen-calc-rebuilt">
    <div class="col-lg-12">
        <div class="calculator-card">
            
            <div class="calculator-body">
                <div class="mb-4">
                    <label class="form-label-custom">Matrix Dimension</label>
                    <div class="d-flex gap-2">
                        <button class="btn btn-outline-indigo active flex-grow-1" data-size="2">2x2 Matrix</button>
                        <button class="btn btn-outline-indigo flex-grow-1" data-size="3">3x3 Matrix</button>
                    </div>
                </div>

                <div id="matrix-input-grid" class="d-flex flex-column gap-2 mb-4 align-items-center">
                    <!-- Grid generated by JS -->
                </div>

                <div class="row g-3">
                    <div class="col-md-12">
                        <label class="form-label-custom">Matrix Controls</label>
                        <div class="d-flex gap-2">
                            <button class="btn btn-outline-danger w-100 rounded-3" id="clear-matrix" style="min-width: 280px; max-width: 100%;"><i class="fas fa-trash-alt me-2"></i>Clear</button>
                            <button class="btn btn-outline-secondary w-100 rounded-3" id="random-matrix" style="min-width: 280px; max-width: 100%;"><i class="fas fa-random me-2"></i>Random</button>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <label class="form-label-custom">Precision</label>
                        <select id="precision-sel" class="form-select form-select-lg rounded-3">
                            <option value="2">2 Decimal Places</option>
                            <option value="4">4 Decimal Places</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="output-card-themed" style="--tool-hue:240;--tool-color:#4338ca;--tool-bg:rgba(79,70,229,.04);">
            <div class="output-hero">
                <span class="output-hero-label">Eigenvalues (λ)</span>
                <div class="output-hero-value fs-3" id="out-eigenvalues">λ₁ = 0, λ₂ = 0</div>
            </div>

            <div class="mt-4">
                <h6 class="fw-bold mb-3"><i class="fas fa-vector-square me-2 text-primary"></i>Eigenvectors (v)</h6>
                <div class="bg-white p-3 rounded-3 border" id="out-eigenvectors">
                    <p class="text-muted small mb-0">Enter a non-zero matrix to see eigenvectors.</p>
                </div>
            </div>

            <div class="mt-4">
                <h6 class="fw-bold mb-3"><i class="fas fa-scroll me-2 text-primary"></i>Mathematical Process</h6>
                <div class="bg-white p-4 rounded-4 border shadow-sm small text-secondary overflow-auto" id="math-steps">
                    Steps will appear here.
                </div>
            </div>

            <div class="row g-2 mt-4">
                <div class="col-md-12">
                    <button class="btn d-block mx-auto btn-dark py-3 px-5 fw-bold rounded-pill shadow-sm" id="copy-solution" style="min-width: 280px; max-width: 100%;"><i class="fas fa-copy me-2"></i>Copy Full Solution</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const $ = id => document.getElementById(id);
    let matrixSize = 2;

    function createGrid(size) {
        matrixSize = size;
        const grid = $('matrix-input-grid');
        grid.innerHTML = '';
        for (let i = 0; i < size; i++) {
            const row = document.createElement('div');
            row.className = 'd-flex gap-2';
            for (let j = 0; j < size; j++) {
                const input = document.createElement('input');
                input.type = 'number';
                input.className = 'form-control matrix-cell text-center';
                input.value = (i === j) ? '1' : '0';
                input.dataset.row = i;
                input.dataset.col = j;
                input.style.width = '70px';
                input.style.height = '60px';
                input.addEventListener('input', calculate);
                row.appendChild(input);
            }
            grid.appendChild(row);
        }
        calculate();
    }

    function getMatrix() {
        const matrix = [];
        for (let i = 0; i < matrixSize; i++) {
            matrix[i] = [];
            for (let j = 0; j < matrixSize; j++) {
                const el = document.querySelector(`.matrix-cell[data-row="${i}"][data-col="${j}"]`);
                matrix[i][j] = parseFloat(el.value) || 0;
            }
        }
        return matrix;
    }

    function calculate() {
        const m = getMatrix();
        const p = parseInt($('precision-sel').value);
        let steps = [];
        let eigenvalues = [];
        let eigenvectors = [];

        if (matrixSize === 2) {
            // Characteristic poly: λ² - tr(A)λ + det(A) = 0
            const tr = m[0][0] + m[1][1];
            const det = (m[0][0] * m[1][1]) - (m[0][1] * m[1][0]);
            
            steps.push(`<strong>1. Characteristic Equation:</strong> det(A - λI) = 0`);
            steps.push(`λ² - (${tr.toFixed(p)})λ + (${det.toFixed(p)}) = 0`);

            // Solve quadratic: λ = [tr ± √(tr² - 4det)] / 2
            const disc = tr*tr - 4*det;
            if (disc >= 0) {
                const l1 = (tr + Math.sqrt(disc)) / 2;
                const l2 = (tr - Math.sqrt(disc)) / 2;
                eigenvalues = [l1, l2];
                $('out-eigenvalues').textContent = `λ₁ = ${l1.toFixed(p)}, λ₂ = ${l2.toFixed(p)}`;

                // Eigenvectors for each λ: (A - λI)v = 0
                eigenvalues.forEach((l, idx) => {
                    const row1 = [m[0][0] - l, m[0][1]];
                    const row2 = [m[1][0], m[1][1] - l];
                    let v;
                    if (Math.abs(row1[0]) > 1e-9 || Math.abs(row1[1]) > 1e-9) {
                        v = [row1[1], -row1[0]];
                    } else if (Math.abs(row2[0]) > 1e-9 || Math.abs(row2[1]) > 1e-9) {
                        v = [row2[1], -row2[0]];
                    } else {
                        v = [1, 0]; // Identity cases
                    }
                    // Normalize
                    const mag = Math.sqrt(v[0]*v[0] + v[1]*v[1]);
                    if (mag > 0) eigenvectors.push(v.map(val => val / mag));
                    else eigenvectors.push([1, 0]);
                });
            } else {
                $('out-eigenvalues').textContent = "Complex Eigenvalues (Unsupported)";
                $('out-eigenvectors').innerHTML = "This tool currently supports real eigenvalues only.";
                return;
            }
        } else {
            // 3x3 placeholder or simplified
            $('out-eigenvalues').textContent = "Use 2x2 for detailed steps.";
            $('math-steps').innerHTML = "3x3 Eigenvalue calculation involves solving a cubic equation, which is not shown here for brevity.";
            return;
        }

        let evHtml = '';
        eigenvectors.forEach((v, i) => {
            evHtml += `<div class="mb-2"><strong>v${i+1} (for λ${i+1}):</strong> [${v.map(val => val.toFixed(p)).join(', ')}]</div>`;
        });
        $('out-eigenvectors').innerHTML = evHtml;

        steps.push(`<br><strong>2. Solving for λ:</strong>`);
        steps.push(`λ = [${tr.toFixed(p)} ± √(${disc.toFixed(p)})] / 2`);
        steps.push(`<br><strong>3. Eigenvectors:</strong> Found by solving (A - λI)v = 0 for each eigenvalue.`);
        $('math-steps').innerHTML = steps.join('<br>');
    }

    document.querySelectorAll('[data-size]').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelectorAll('[data-size]').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            createGrid(parseInt(btn.dataset.size));
        });
    });

    $('clear-matrix').addEventListener('click', () => {
        document.querySelectorAll('.matrix-cell').forEach(c => c.value = '0');
        calculate();
    });

    $('random-matrix').addEventListener('click', () => {
        document.querySelectorAll('.matrix-cell').forEach(c => {
            c.value = Math.floor(Math.random() * 10);
        });
        calculate();
    });

    $('precision-sel').addEventListener('change', calculate);

    $('copy-solution').addEventListener('click', function() {
        const text = `Matrix Eigenvalues\n${$('out-eigenvalues').textContent}\nGenerated by ToolsHub`;
        navigator.clipboard.writeText(text).then(() => {
            const o = this.innerHTML;
            this.innerHTML = '<i class="fas fa-check me-2"></i>Copied!';
            setTimeout(() => this.innerHTML = o, 2000);
        });
    });

    createGrid(2);
});
</script>

<style>
.eigen-calc-rebuilt .calculator-card { background: #fff; border: 1px solid #e5e7eb; border-radius: 20px; padding: 2rem; box-shadow: 0 4px 24px rgba(0,0,0,.04); }
.eigen-calc-rebuilt .calculator-header { display: flex; align-items: center; gap: 1rem; margin-bottom: 2rem; }
.eigen-calc-rebuilt .calculator-header h4 { margin: 0; font-weight: 800; color: #1e293b; }
.eigen-calc-rebuilt .calculator-header p { margin: 0; font-size: .9rem; color: #64748b; }
.eigen-calc-rebuilt .tool-icon-circle { width: 56px; height: 56px; border-radius: 14px; display: flex; align-items: center; justify-content: center; font-size: 1.4rem; flex-shrink: 0; }
.eigen-calc-rebuilt .form-label-custom { font-size: .8rem; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: .5px; margin-bottom: .4rem; display: block; }
.btn-outline-indigo { border: 1.5px solid #e0e7ff; color: #4338ca; font-weight: 600; border-radius: 12px; transition: all 0.2s; }
.btn-outline-indigo:hover, .btn-outline-indigo.active { background: #4f46e5; color: #fff; border-color: #4f46e5; box-shadow: 0 4px 12px rgba(79,70,229,.2); }
.matrix-cell { font-weight: bold; font-size: 1.1rem; border-radius: 10px !important; border: 2px solid #f1f5f9; transition: all 0.2s; }
.matrix-cell:focus { border-color: #4f46e5; box-shadow: none; background: #f5f3ff; }

.features-grid { grid-template-columns: 1fr !important; }
.features-grid > div { margin-bottom: 1rem; }
</style>

<?php /**PATH D:\Xamp\htdocs\ToolsHub\resources\views\tools\interactive\eigenvalue-eigenvector-calculator.blade.php ENDPATH**/ ?>