<div class="row g-4 house-flipping-profit-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">Purchase Price ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="hf-buy" class="form-control form-control-lg" value="200000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Rehab Costs ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="hf-rehab" class="form-control form-control-lg" value="40000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">After Repair Value ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="hf-arv" class="form-control form-control-lg" value="300000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Holding Costs ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="hf-hold" class="form-control form-control-lg" value="5000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Closing Costs (%)</label><div class="input-group"><input type="number" id="hf-close" class="form-control form-control-lg" value="6" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">Agent Commission (%)</label><div class="input-group"><input type="number" id="hf-agent" class="form-control form-control-lg" value="5" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:40;--tool-color:#f59e0b;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">House Flipping Profit Calculator</span><div class="output-hero-value" id="house-val">—</div><span class="output-hero-unit" id="house-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">NET PROFIT</span><span class="stat-card-value" style="color:#22c55e" id="hf-profit">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">ROI</span><span class="stat-card-value" style="color:#3b82f6" id="hf-roi">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#ef4444;background:rgba(0,0,0,.02);"><span class="stat-card-label">TOTAL COSTS</span><span class="stat-card-value" style="color:#ef4444" id="hf-costs">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#f59e0b;background:rgba(0,0,0,.02);"><span class="stat-card-label">PROFIT MARGIN</span><span class="stat-card-value" style="color:#f59e0b" id="hf-margin">—</span></div></div></div><div class="mt-4" id="house-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="house-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="house-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="house-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const buy=parseFloat($('hf-buy').value)||0,rehab=parseFloat($('hf-rehab').value)||0,arv=parseFloat($('hf-arv').value)||0,hold=parseFloat($('hf-hold').value)||0,close=(parseFloat($('hf-close').value)||0)/100,agent=(parseFloat($('hf-agent').value)||0)/100;
const closeCost=arv*close,agentCost=arv*agent,totalCosts=buy+rehab+hold+closeCost+agentCost,profit=arv-totalCosts,roi=totalCosts>0?(profit/totalCosts*100):0,margin=arv>0?(profit/arv*100):0;
$('house-val').textContent=fmt(profit);$('hf-profit').textContent=fmt(profit);$('hf-roi').textContent=roi.toFixed(1)+'%';$('hf-costs').textContent=fmt(totalCosts);$('hf-margin').textContent=margin.toFixed(1)+'%';
$('house-st').textContent=profit>0?'PROFITABLE FLIP':'LOSS';$('house-st').style.color=profit>0?'#22c55e':'#ef4444';
let ins=[];ins.push('Net profit: <strong>'+fmt(profit)+'</strong> on ARV of '+fmt(arv)+'.');ins.push('ROI: <strong>'+roi.toFixed(1)+'%</strong>. Total invested: '+fmt(totalCosts)+'.');
if(profit<0)ins.push('⚠️ This flip would result in a loss. Consider negotiating purchase price.');
$('house-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['hf-buy','hf-rehab','hf-arv','hf-hold','hf-close','hf-agent'].forEach(id=>$(id).addEventListener('input',calc));
$('house-cb').addEventListener('click',calc);
$('house-cp').addEventListener('click',function(){navigator.clipboard.writeText('House Flipping Profit Calculator: '+$('house-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('house-rs').addEventListener('click',()=>{$('hf-buy').value=200000;$('hf-rehab').value=40000;$('hf-arv').value=300000;$('hf-hold').value=5000;$('hf-close').value=6;$('hf-agent').value=5;calc();});calc();});
</script>
<style>.house-flipping-profit-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.house-flipping-profit-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.house-flipping-profit-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.house-flipping-profit-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.house-flipping-profit-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.house-flipping-profit-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style><?php /**PATH D:\Xamp\htdocs\ToolsHub\resources\views\tools\interactive\house-flipping-profit-calculator.blade.php ENDPATH**/ ?>