<div class="interactive-tool-grid cubic-yard-calculator">
    <div class="calculator-card">
        

        <div class="calculator-body">
            <div class="form-group-custom mb-3">
                <label class="form-label-custom">Length (feet)</label>
                <input type="number" id="length-ft" class="form-control-custom cy-input" placeholder="e.g. 50">
            </div>

            <div class="form-group-custom mb-3">
                <label class="form-label-custom">Width (feet)</label>
                <input type="number" id="width-ft" class="form-control-custom cy-input" placeholder="e.g. 20">
            </div>

            <div class="form-group-custom mb-4">
                <label class="form-label-custom">Depth (inches)</label>
                <input type="number" id="depth-in" class="form-control-custom cy-input" placeholder="e.g. 3">
            </div>

            <div class="alert alert-info py-2" style="font-size: 0.85rem; border-radius: 10px;">
                <i class="fas fa-info-circle me-1"></i> (Length × Width × Depth/12) / 27 = Cubic Yards
            </div>
        </div>
    </div>

    <div class="result-panel">
        <div class="result-card-v2">
            <span class="result-label">Volume (Cubic Yards)</span>
            <div class="result-main-value" id="result-cy">0.00</div>
            
            <div class="result-sub-stats">
                <div class="stat-item border-end pe-3">
                    <span class="stat-label">Cubic Feet</span>
                    <span class="stat-value" id="stat-cf">0.0</span>
                </div>
                <div class="stat-item ps-3">
                    <span class="stat-label">Truck Loads</span>
                    <span class="stat-value" id="stat-loads">0.0</span>
                </div>
            </div>

            <button class="btn d-block mx-auto btn-accent mt-3 py-3 px-5 fw-bold rounded-pill shadow-sm" id="copy-result" style="min-width: 280px; max-width: 100%;">
                <i class="fas fa-copy me-2"></i> Copy Volume
            </button>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    function calculate() {
        const l = parseFloat(document.getElementById('length-ft').value) || 0;
        const w = parseFloat(document.getElementById('width-ft').value) || 0;
        const d = (parseFloat(document.getElementById('depth-in').value) || 0) / 12;

        const cf = l * w * d;
        const cy = cf / 27;

        document.getElementById('result-cy').innerText = cy.toFixed(2);
        document.getElementById('stat-cf').innerText = cf.toFixed(1);
        document.getElementById('stat-loads').innerText = (cy / 10).toFixed(1); // Avg 10cy per truck
    }

    document.querySelectorAll('.cy-input').forEach(el => {
        el.addEventListener('input', calculate);
    });

    document.getElementById('copy-result').addEventListener('click', function() {
        const text = `Volume Calculation Results:\nCubic Yards: ${document.getElementById('result-cy').innerText}\nCubic Feet: ${document.getElementById('stat-cf').innerText}\nGenerated by ToolsHub Construction.`;
        navigator.clipboard.writeText(text).then(() => {
            const btn = this;
            const originalText = btn.innerHTML;
            btn.innerHTML = '<i class="fas fa-check me-2"></i> Copied!';
            setTimeout(() => { btn.innerHTML = originalText; }, 2000);
        });
    });

    calculate();
});
</script>

<?php /**PATH D:\Xamp\htdocs\ToolsHub\resources\views\tools\interactive\cubic-yard-calculator.blade.php ENDPATH**/ ?>