<div class="row g-4 capital-gains-tax-calculator-rebuilt"><div class="col-lg-12"><div class="calculator-card"><div class="calculator-body"><div class="row g-3"><div class="col-md-6"><label class="form-label-custom">Purchase Price ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="cgt-cost" class="form-control form-control-lg" value="50000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Sale Price ($)</label><div class="input-group"><span class="input-group-text bg-light fw-bold">$</span><input type="number" id="cgt-sale" class="form-control form-control-lg" value="75000" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Holding Period (Months)</label><div class="input-group"><input type="number" id="cgt-hold" class="form-control form-control-lg" value="18" min="0"></div></div><div class="col-md-6"><label class="form-label-custom">Short-Term Tax Rate (%)</label><div class="input-group"><input type="number" id="cgt-str" class="form-control form-control-lg" value="32" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">Long-Term Tax Rate (%)</label><div class="input-group"><input type="number" id="cgt-ltr" class="form-control form-control-lg" value="15" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div><div class="col-md-6"><label class="form-label-custom">State Tax Rate (%)</label><div class="input-group"><input type="number" id="cgt-state" class="form-control form-control-lg" value="5" min="0"><span class="input-group-text bg-light fw-bold">%</span></div></div></div></div></div></div>
<div class="col-lg-12"><div class="output-card-themed" style="--tool-hue:270;--tool-color:#7c3aed;--tool-bg:rgba(0,0,0,.02);"><div class="output-hero"><span class="output-hero-label">Capital Gains Tax Calculator</span><div class="output-hero-value" id="capital-val">—</div><span class="output-hero-unit" id="capital-st">—</span></div><div class="row g-3 mt-3"><div class="col-md-3"><div class="stat-card" style="border-color:#22c55e;background:rgba(0,0,0,.02);"><span class="stat-card-label">CAPITAL GAIN</span><span class="stat-card-value" style="color:#22c55e" id="cgt-gain">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#ef4444;background:rgba(0,0,0,.02);"><span class="stat-card-label">FEDERAL TAX</span><span class="stat-card-value" style="color:#ef4444" id="cgt-tax">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#f59e0b;background:rgba(0,0,0,.02);"><span class="stat-card-label">STATE TAX</span><span class="stat-card-value" style="color:#f59e0b" id="cgt-state-t">—</span></div></div><div class="col-md-3"><div class="stat-card" style="border-color:#3b82f6;background:rgba(0,0,0,.02);"><span class="stat-card-label">NET PROCEEDS</span><span class="stat-card-value" style="color:#3b82f6" id="cgt-net">—</span></div></div></div><div class="mt-4" id="capital-ins"></div>
<div class="row g-2 mt-4"><div class="col-md-4"><button class="btn d-block mx-auto btn-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="capital-cp"><i class="fas fa-copy me-2"></i>Copy Summary</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-dark py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="capital-rs"><i class="fas fa-rotate-left me-2"></i>Reset Fields</button></div><div class="col-md-4"><button class="btn d-block mx-auto btn-outline-primary py-3 px-4 fw-bold rounded-pill shadow-sm w-100" id="capital-cb"><i class="fas fa-calculator me-2"></i>Calculate</button></div></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){
const $=id=>document.getElementById(id);function fmt(v){return'$'+Math.round(v).toLocaleString();}
function calc(){const cost=parseFloat($('cgt-cost').value)||0,sale=parseFloat($('cgt-sale').value)||0,hold=parseFloat($('cgt-hold').value)||0,str=(parseFloat($('cgt-str').value)||0)/100,ltr=(parseFloat($('cgt-ltr').value)||0)/100,sr=(parseFloat($('cgt-state').value)||0)/100;
const gain=sale-cost,isLT=hold>=12,rate=isLT?ltr:str,fedTax=Math.max(0,gain*rate),stateTax=Math.max(0,gain*sr),totalTax=fedTax+stateTax,net=sale-totalTax;
$('capital-val').textContent=fmt(totalTax);$('cgt-gain').textContent=fmt(gain);$('cgt-tax').textContent=fmt(fedTax);$('cgt-state-t').textContent=fmt(stateTax);$('cgt-net').textContent=fmt(net);
$('capital-st').textContent=isLT?'LONG-TERM ('+ltr*100+'%)':'SHORT-TERM ('+str*100+'%)';$('capital-st').style.color=isLT?'#22c55e':'#f59e0b';
let ins=[];ins.push('Capital gain of <strong>'+fmt(gain)+'</strong> classified as <strong>'+(isLT?'long-term':'short-term')+'</strong>.');
ins.push('Total tax: <strong>'+fmt(totalTax)+'</strong> (federal: '+fmt(fedTax)+', state: '+fmt(stateTax)+').');
if(gain<0)ins.push('📉 Capital loss of '+fmt(Math.abs(gain))+'. Can offset other gains up to \$3,000/yr.');
$('capital-ins').innerHTML='<h6 class="fw-bold mb-2"><i class="fas fa-lightbulb me-2 text-warning"></i>Analysis</h6><ul class="list-unstyled mb-0 small">'+ins.map(x=>'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>'+x+'</li>').join('')+'</ul>';}
['cgt-cost','cgt-sale','cgt-hold','cgt-str','cgt-ltr','cgt-state'].forEach(id=>$(id).addEventListener('input',calc));
$('capital-cb').addEventListener('click',calc);
$('capital-cp').addEventListener('click',function(){navigator.clipboard.writeText('Capital Gains Tax Calculator: '+$('capital-val').textContent+' — ToolsHub').then(()=>{const o=this.innerHTML;this.innerHTML='<i class="fas fa-check me-2"></i>Copied!';setTimeout(()=>this.innerHTML=o,2000);});});
$('capital-rs').addEventListener('click',()=>{$('cgt-cost').value=50000;$('cgt-sale').value=75000;$('cgt-hold').value=18;$('cgt-str').value=32;$('cgt-ltr').value=15;$('cgt-state').value=5;calc();});calc();});
</script>
<style>.capital-gains-tax-calculator-rebuilt .calculator-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:2rem;box-shadow:0 4px 24px rgba(0,0,0,.04)}.capital-gains-tax-calculator-rebuilt .calculator-header{display:flex;align-items:center;gap:1.25rem;margin-bottom:2rem}.capital-gains-tax-calculator-rebuilt .calculator-header h4{margin:0;font-weight:700;font-size:1.1rem;color:#1e293b}.capital-gains-tax-calculator-rebuilt .calculator-header p{margin:0;font-size:.85rem;color:#64748b}.capital-gains-tax-calculator-rebuilt .tool-icon-circle{width:56px;height:56px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.4rem;flex-shrink:0}.capital-gains-tax-calculator-rebuilt .form-label-custom{font-size:.75rem;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:.8px;margin-bottom:.4rem;display:block}</style><?php /**PATH D:\Xamp\htdocs\ToolsHub\resources\views\tools\interactive\capital-gains-tax-calculator.blade.php ENDPATH**/ ?>