<?php
$dir=__DIR__.'/../resources/views/tools/interactive/';
function tpl($icon,$h5,$sub,$fields,$formula,$js){
return '<div class="interactive-wrapper">
<div class="card shadow-sm border-0 mb-4" style="border-radius:24px;background:#fff;word-break:break-word">
<div class="bg-white border-bottom-0 py-4 px-4" style="border-radius:24px 24px 0 0">
<div class="d-flex align-items-center justify-content-between flex-wrap gap-2">
<div class="d-flex align-items-center"><div style="width:48px;height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.25rem;background:#eef2ff"><i class="'.$icon.' text-primary"></i></div>
<div class="ms-3"><h5 class="mb-0 fw-bold text-dark">'.$h5.'</h5><p class="text-muted small mb-0">'.$sub.'</p></div></div>
<button class="btn btn-sm rounded-pill px-3" id="btn-reset" style="background:#f1f5f9;font-weight:600"><i class="fas fa-undo me-1"></i>Reset</button>
</div></div>
<div class="px-4 pb-4" style="overflow-x:auto">
'.$fields.'
<div class="mt-4 text-center"><button class="btn btn-primary btn-lg rounded-pill px-5 shadow-sm" id="btn-calc" style="min-width:260px;max-width:100%"><i class="fas fa-calculator me-2"></i>Calculate</button></div>
<div class="mt-3 p-3 rounded-4 border" style="background:#f8fafc"><p class="mb-0 small text-muted"><i class="fas fa-info-circle text-primary me-2"></i>'.$formula.'</p></div>
</div></div>
<div id="res" class="card shadow-sm border-0 d-none mb-4" style="border-radius:24px;background:#fff;word-break:break-word">
<div class="bg-white border-bottom-0 py-4 px-4" style="border-radius:24px 24px 0 0">
<div class="d-flex align-items-center justify-content-between flex-wrap gap-2">
<div class="d-flex align-items-center"><div style="width:48px;height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.25rem;background:#ecfdf5"><i class="fas fa-check-circle text-success"></i></div>
<div class="ms-3"><h5 class="mb-0 fw-bold text-dark">Result</h5><p class="text-muted small mb-0">Detailed breakdown</p></div></div>
<button class="btn btn-success btn-sm rounded-pill px-4 shadow-sm" id="btn-copy" style="min-width:120px"><i class="fas fa-copy me-1"></i>Copy</button>
</div></div>
<div class="px-4 pb-4" style="overflow-x:auto">
<div class="p-4 rounded-4 bg-light border text-center mb-3"><div class="small fw-bold text-uppercase text-muted mb-1">RESULT</div><div class="display-4 fw-bold text-dark" id="out-main">—</div><div class="small text-muted fw-bold" id="out-unit"></div></div>
<div id="out-detail" class="row g-3 mb-3"></div>
<div class="p-4 rounded-4 bg-light border shadow-sm"><h6 class="fw-bold mb-3 small text-uppercase text-muted" style="letter-spacing:1px"><i class="fas fa-lightbulb text-warning me-2"></i>Insights</h6><div id="out-ins" class="small text-secondary"></div></div>
</div></div></div>
<style>.form-control-lg,.form-select-lg{border:1.5px solid #e2e8f0;border-radius:12px;font-size:1.05rem;padding:.75rem 1rem}.form-control:focus,.form-select:focus{border-color:#4f46e5;box-shadow:0 0 0 4px rgba(79,70,229,.1)}</style>
<script>'.$js.'</script>';
}

// 5. Molarity Calculator
file_put_contents($dir.'molarity-calculator.blade.php', tpl('fas fa-flask-vial','Molarity Calculator','Calculate solution concentration from moles and volume',
'<div class="row g-3">
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Moles of Solute</label><input type="number" id="in-n" class="form-control form-control-lg" value="1" step="0.01"></div>
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Volume (L)</label><input type="number" id="in-v" class="form-control form-control-lg" value="1" step="0.01"></div>
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Temperature</label><div class="input-group"><input type="number" id="in-t" class="form-control form-control-lg" value="25"><select id="in-tu" class="form-select" style="max-width:70px"><option value="C">°C</option><option value="K">K</option></select></div></div></div>',
'<b>Formula:</b> M = n / V where M=molarity(mol/L), n=moles, V=volume(L)',
'document.addEventListener("DOMContentLoaded",function(){document.getElementById("btn-calc").addEventListener("click",function(){var n=parseFloat(document.getElementById("in-n").value)||0,v=parseFloat(document.getElementById("in-v").value)||0;if(v===0)return;var m=n/v;document.getElementById("out-main").textContent=m.toFixed(4);document.getElementById("out-unit").textContent="mol/L (M)";document.getElementById("out-detail").innerHTML=\'<div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Moles</div><div class="h5 fw-bold mb-0 text-primary">\'+n.toFixed(4)+\'</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Volume</div><div class="h5 fw-bold mb-0 text-info">\'+v.toFixed(4)+\' L</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">mM</div><div class="h5 fw-bold mb-0 text-success">\'+(m*1000).toFixed(2)+\'</div></div></div>\';var ins=["Molarity = "+n+" / "+v+" = <b>"+m.toFixed(4)+" M</b>","Equivalent to <b>"+(m*1000).toFixed(2)+" mM</b> (millimolar)"];document.getElementById("out-ins").innerHTML=\'<ul class="list-unstyled mb-0">\'+ins.map(function(i){return\'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>\'+i+\'</li>\';}).join("")+"</ul>";document.getElementById("res").classList.remove("d-none");document.getElementById("res").scrollIntoView({behavior:"smooth"});});document.getElementById("btn-reset").addEventListener("click",function(){document.getElementById("in-n").value=1;document.getElementById("in-v").value=1;document.getElementById("res").classList.add("d-none");});document.getElementById("btn-copy").addEventListener("click",function(){navigator.clipboard.writeText("Molarity: "+document.getElementById("out-main").textContent+" mol/L — ToolsHub");var b=this,o=b.innerHTML;b.innerHTML="<i class=\\"fas fa-check me-1\\"></i>Copied!";setTimeout(function(){b.innerHTML=o;},2000);});});'));
echo "5. molarity-calculator\n";

// 6. Percent Yield
file_put_contents($dir.'percent-yield-calculator.blade.php', tpl('fas fa-percent','Percent Yield Calculator','Calculate reaction efficiency from actual and theoretical yield',
'<div class="row g-3">
<div class="col-md-6"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Actual Yield (g)</label><input type="number" id="in-a" class="form-control form-control-lg" value="8.5" step="0.01"></div>
<div class="col-md-6"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Theoretical Yield (g)</label><input type="number" id="in-th" class="form-control form-control-lg" value="10" step="0.01"></div></div>',
'<b>Formula:</b> % Yield = (Actual Yield / Theoretical Yield) × 100',
'document.addEventListener("DOMContentLoaded",function(){document.getElementById("btn-calc").addEventListener("click",function(){var a=parseFloat(document.getElementById("in-a").value)||0,t=parseFloat(document.getElementById("in-th").value)||0;if(t===0)return;var y=(a/t)*100;document.getElementById("out-main").textContent=y.toFixed(2)+"%";document.getElementById("out-unit").textContent="Percent Yield";document.getElementById("out-detail").innerHTML=\'<div class="col-6"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Actual</div><div class="h5 fw-bold mb-0 text-primary">\'+a+\' g</div></div></div><div class="col-6"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Theoretical</div><div class="h5 fw-bold mb-0 text-info">\'+t+\' g</div></div></div>\';var ins=["% Yield = ("+a+" / "+t+") × 100 = <b>"+y.toFixed(2)+"%</b>"];if(y>100)ins.push("⚠ Yield >100% suggests impurities or measurement error.");else if(y>90)ins.push("Excellent yield — very efficient reaction.");else if(y<50)ins.push("Low yield — consider optimizing conditions.");document.getElementById("out-ins").innerHTML=\'<ul class="list-unstyled mb-0">\'+ins.map(function(i){return\'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>\'+i+\'</li>\';}).join("")+"</ul>";document.getElementById("res").classList.remove("d-none");document.getElementById("res").scrollIntoView({behavior:"smooth"});});document.getElementById("btn-reset").addEventListener("click",function(){document.getElementById("in-a").value=8.5;document.getElementById("in-th").value=10;document.getElementById("res").classList.add("d-none");});document.getElementById("btn-copy").addEventListener("click",function(){navigator.clipboard.writeText("Percent Yield: "+document.getElementById("out-main").textContent+" — ToolsHub");var b=this,o=b.innerHTML;b.innerHTML="<i class=\\"fas fa-check me-1\\"></i>Copied!";setTimeout(function(){b.innerHTML=o;},2000);});});'));
echo "6. percent-yield-calculator\n";

// 7. Boiling Point Calculator
file_put_contents($dir.'boiling-point-calculator.blade.php', tpl('fas fa-temperature-high','Boiling Point Calculator','Calculate boiling point elevation for solutions',
'<div class="row g-3">
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Kb (°C/m)</label><input type="number" id="in-kb" class="form-control form-control-lg" value="0.512" step="0.001"><div class="form-text">Water=0.512</div></div>
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Molality (m)</label><input type="number" id="in-m" class="form-control form-control-lg" value="1" step="0.01"></div>
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Van\'t Hoff (i)</label><input type="number" id="in-i" class="form-control form-control-lg" value="1" step="1"><div class="form-text">NaCl=2, CaCl₂=3</div></div>
<div class="col-md-6"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Solvent BP</label><div class="input-group"><input type="number" id="in-bp" class="form-control form-control-lg" value="100"><select id="in-tu" class="form-select" style="max-width:70px"><option value="C">°C</option><option value="K">K</option><option value="F">°F</option></select></div></div>
<div class="col-md-6"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Pressure</label><div class="input-group"><input type="number" id="in-pr" class="form-control form-control-lg" value="1" step="0.01"><select id="in-pu" class="form-select" style="max-width:80px"><option value="atm">atm</option><option value="Pa">Pa</option></select></div></div></div>',
'<b>Formula:</b> ΔTb = i × Kb × m (boiling point elevation)',
'document.addEventListener("DOMContentLoaded",function(){document.getElementById("btn-calc").addEventListener("click",function(){var kb=parseFloat(document.getElementById("in-kb").value)||0,m=parseFloat(document.getElementById("in-m").value)||0,i=parseFloat(document.getElementById("in-i").value)||1,bp=parseFloat(document.getElementById("in-bp").value)||100;var dt=i*kb*m;var nbp=bp+dt;document.getElementById("out-main").textContent=nbp.toFixed(3)+"°C";document.getElementById("out-unit").textContent="New Boiling Point";document.getElementById("out-detail").innerHTML=\'<div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">ΔTb</div><div class="h5 fw-bold mb-0 text-danger">\'+dt.toFixed(4)+\'°C</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Original BP</div><div class="h5 fw-bold mb-0 text-info">\'+bp+\'°C</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Elevation</div><div class="h5 fw-bold mb-0 text-warning">+\'+dt.toFixed(3)+\'°C</div></div></div>\';var ins=["ΔTb = "+i+" × "+kb+" × "+m+" = <b>"+dt.toFixed(4)+"°C</b>","New BP = "+bp+" + "+dt.toFixed(4)+" = <b>"+nbp.toFixed(3)+"°C</b>"];document.getElementById("out-ins").innerHTML=\'<ul class="list-unstyled mb-0">\'+ins.map(function(x){return\'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>\'+x+\'</li>\';}).join("")+"</ul>";document.getElementById("res").classList.remove("d-none");document.getElementById("res").scrollIntoView({behavior:"smooth"});});document.getElementById("btn-reset").addEventListener("click",function(){document.getElementById("in-kb").value=0.512;document.getElementById("in-m").value=1;document.getElementById("in-i").value=1;document.getElementById("in-bp").value=100;document.getElementById("res").classList.add("d-none");});document.getElementById("btn-copy").addEventListener("click",function(){navigator.clipboard.writeText("Boiling Point: "+document.getElementById("out-main").textContent+" — ToolsHub");var b=this,o=b.innerHTML;b.innerHTML="<i class=\\"fas fa-check me-1\\"></i>Copied!";setTimeout(function(){b.innerHTML=o;},2000);});});'));
echo "7. boiling-point-calculator\n";

// 8. Scientific Notation
file_put_contents($dir.'scientific-notation-calculator.blade.php', tpl('fas fa-superscript','Scientific Notation Calculator','Convert numbers to and from scientific notation',
'<div class="row g-3">
<div class="col-12"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Enter Number</label><input type="text" id="in-num" class="form-control form-control-lg" value="299792458" placeholder="e.g. 0.00045 or 3.5e8"></div></div>',
'<b>Formula:</b> N = a × 10ⁿ where 1 ≤ |a| < 10',
'document.addEventListener("DOMContentLoaded",function(){document.getElementById("btn-calc").addEventListener("click",function(){var s=document.getElementById("in-num").value.trim(),n=parseFloat(s);if(isNaN(n)){document.getElementById("out-main").textContent="Invalid";return;}var e=n===0?0:Math.floor(Math.log10(Math.abs(n)));var m=n/Math.pow(10,e);document.getElementById("out-main").textContent=m.toFixed(6)+" × 10^"+e;document.getElementById("out-unit").textContent="Scientific Notation";document.getElementById("out-detail").innerHTML=\'<div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Decimal</div><div class="h5 fw-bold mb-0 text-primary" style="word-break:break-all">\'+n.toString()+\'</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Exponent</div><div class="h5 fw-bold mb-0 text-info">\'+e+\'</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Mantissa</div><div class="h5 fw-bold mb-0 text-success">\'+m.toFixed(6)+\'</div></div></div>\';var ins=["Standard form: <b>"+m.toFixed(6)+" × 10^"+e+"</b>","E-notation: <b>"+n.toExponential()+"</b>"];if(Math.abs(n)>1e6)ins.push("Very large number — scientific notation simplifies representation.");else if(Math.abs(n)<0.001&&n!==0)ins.push("Very small number — scientific notation avoids leading zeros.");document.getElementById("out-ins").innerHTML=\'<ul class="list-unstyled mb-0">\'+ins.map(function(i){return\'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>\'+i+\'</li>\';}).join("")+"</ul>";document.getElementById("res").classList.remove("d-none");document.getElementById("res").scrollIntoView({behavior:"smooth"});});document.getElementById("btn-reset").addEventListener("click",function(){document.getElementById("in-num").value="299792458";document.getElementById("res").classList.add("d-none");});document.getElementById("btn-copy").addEventListener("click",function(){navigator.clipboard.writeText("Scientific Notation: "+document.getElementById("out-main").textContent+" — ToolsHub");var b=this,o=b.innerHTML;b.innerHTML="<i class=\\"fas fa-check me-1\\"></i>Copied!";setTimeout(function(){b.innerHTML=o;},2000);});});'));
echo "8. scientific-notation-calculator\n";

// 9. Significant Figures
file_put_contents($dir.'significant-figures-calculator.blade.php', tpl('fas fa-hashtag','Significant Figures Calculator','Count significant figures and round numbers precisely',
'<div class="row g-3">
<div class="col-md-8"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Enter Number</label><input type="text" id="in-num" class="form-control form-control-lg" value="0.00340" placeholder="e.g. 0.00340"></div>
<div class="col-md-4"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Round To (sig figs)</label><input type="number" id="in-round" class="form-control form-control-lg" value="" placeholder="optional" min="1" max="20"></div></div>',
'<b>Rules:</b> All non-zero digits are significant. Zeros between non-zero digits are significant. Trailing zeros after decimal point are significant.',
'document.addEventListener("DOMContentLoaded",function(){function countSF(s){s=s.trim().replace(/^-/,"");if(s.indexOf("e")!==-1||s.indexOf("E")!==-1){var parts=s.split(/[eE]/);s=parts[0];}s=s.replace(/^0+\\.?/,".");var sf=0;var started=false;for(var i=0;i<s.length;i++){if(s[i]===".")continue;if(s[i]!=="0")started=true;if(started)sf++;}return Math.max(sf,1);}document.getElementById("btn-calc").addEventListener("click",function(){var s=document.getElementById("in-num").value.trim(),n=parseFloat(s);if(isNaN(n)){document.getElementById("out-main").textContent="Invalid";return;}var sf=countSF(s);var rnd=parseInt(document.getElementById("in-round").value);var rounded=rnd>0?parseFloat(n.toPrecision(rnd)):n;document.getElementById("out-main").textContent=sf;document.getElementById("out-unit").textContent="Significant Figures";document.getElementById("out-detail").innerHTML=\'<div class="col-6"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Original</div><div class="h5 fw-bold mb-0 text-primary">\'+s+\'</div></div></div><div class="col-6"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Rounded</div><div class="h5 fw-bold mb-0 text-success">\'+(rnd>0?rounded.toPrecision(rnd):s)+\'</div></div></div>\';var ins=["Input <b>"+s+"</b> has <b>"+sf+"</b> significant figures"];if(rnd>0)ins.push("Rounded to "+rnd+" sig figs: <b>"+rounded.toPrecision(rnd)+"</b>");document.getElementById("out-ins").innerHTML=\'<ul class="list-unstyled mb-0">\'+ins.map(function(i){return\'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>\'+i+\'</li>\';}).join("")+"</ul>";document.getElementById("res").classList.remove("d-none");document.getElementById("res").scrollIntoView({behavior:"smooth"});});document.getElementById("btn-reset").addEventListener("click",function(){document.getElementById("in-num").value="0.00340";document.getElementById("in-round").value="";document.getElementById("res").classList.add("d-none");});document.getElementById("btn-copy").addEventListener("click",function(){navigator.clipboard.writeText("Sig Figs: "+document.getElementById("out-main").textContent+" — ToolsHub");var b=this,o=b.innerHTML;b.innerHTML="<i class=\\"fas fa-check me-1\\"></i>Copied!";setTimeout(function(){b.innerHTML=o;},2000);});});'));
echo "9. significant-figures-calculator\n";

// 10. Grams to Moles
file_put_contents($dir.'grams-to-moles-calculator.blade.php', tpl('fas fa-weight-scale','Grams to Moles Calculator','Convert mass in grams to moles using molar mass',
'<div class="row g-3">
<div class="col-md-6"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Mass (grams)</label><input type="number" id="in-g" class="form-control form-control-lg" value="18" step="0.01"></div>
<div class="col-md-6"><label class="form-label small fw-bold text-secondary text-uppercase mb-2">Molar Mass (g/mol)</label><input type="number" id="in-mm" class="form-control form-control-lg" value="18.015" step="0.001"><div class="form-text">H₂O=18.015, NaCl=58.44, C₆H₁₂O₆=180.16</div></div></div>',
'<b>Formula:</b> n = mass / M where n=moles, M=molar mass (g/mol)',
'document.addEventListener("DOMContentLoaded",function(){document.getElementById("btn-calc").addEventListener("click",function(){var g=parseFloat(document.getElementById("in-g").value)||0,mm=parseFloat(document.getElementById("in-mm").value)||0;if(mm===0)return;var n=g/mm;var particles=n*6.022e23;document.getElementById("out-main").textContent=n.toFixed(6);document.getElementById("out-unit").textContent="moles";document.getElementById("out-detail").innerHTML=\'<div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Mass</div><div class="h5 fw-bold mb-0 text-primary">\'+g+\' g</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Molar Mass</div><div class="h5 fw-bold mb-0 text-info">\'+mm+\' g/mol</div></div></div><div class="col-4"><div class="p-3 rounded-4 bg-light border text-center"><div class="small fw-bold text-uppercase text-muted mb-1">Particles</div><div class="h5 fw-bold mb-0 text-success">\'+particles.toExponential(3)+\'</div></div></div>\';var ins=["n = "+g+" / "+mm+" = <b>"+n.toFixed(6)+" mol</b>","= <b>"+particles.toExponential(3)+"</b> molecules/atoms (× Avogadro\'s number)"];document.getElementById("out-ins").innerHTML=\'<ul class="list-unstyled mb-0">\'+ins.map(function(i){return\'<li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>\'+i+\'</li>\';}).join("")+"</ul>";document.getElementById("res").classList.remove("d-none");document.getElementById("res").scrollIntoView({behavior:"smooth"});});document.getElementById("btn-reset").addEventListener("click",function(){document.getElementById("in-g").value=18;document.getElementById("in-mm").value=18.015;document.getElementById("res").classList.add("d-none");});document.getElementById("btn-copy").addEventListener("click",function(){navigator.clipboard.writeText("Moles: "+document.getElementById("out-main").textContent+" mol — ToolsHub");var b=this,o=b.innerHTML;b.innerHTML="<i class=\\"fas fa-check me-1\\"></i>Copied!";setTimeout(function(){b.innerHTML=o;},2000);});});'));
echo "10. grams-to-moles-calculator\n";

echo "Batch 1 done (tools 5-10)\n";
