<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Internal Link — Semantic link pair between two tools.
 *
 * Generated by the InternalLinkingService with keyword-rich anchor text
 * and relevance scoring. Supports human review workflow.
 */
class InternalLink extends Model
{
    protected $fillable = [
        'source_tool_slug',
        'target_tool_slug',
        'anchor_text_primary',
        'anchor_text_variations',
        'relevance_score',
        'placement_zone',
        'is_active',
        'auto_generated',
        'human_reviewed',
        'last_refreshed_at',
    ];

    protected $casts = [
        'anchor_text_variations' => 'array',
        'relevance_score'        => 'decimal:2',
        'is_active'              => 'boolean',
        'auto_generated'         => 'boolean',
        'human_reviewed'         => 'boolean',
        'last_refreshed_at'      => 'datetime',
    ];

    // ─── Scopes ──────────────────────────────────────────────────

    /**
     * Get outgoing links from a specific tool.
     */
    public function scopeFrom($query, string $slug)
    {
        return $query->where('source_tool_slug', $slug);
    }

    /**
     * Get incoming links to a specific tool.
     */
    public function scopeTo($query, string $slug)
    {
        return $query->where('target_tool_slug', $slug);
    }

    /**
     * Only active links.
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Only human-reviewed links.
     */
    public function scopeReviewed($query)
    {
        return $query->where('human_reviewed', true);
    }

    /**
     * Ordered by relevance (highest first).
     */
    public function scopeByRelevance($query)
    {
        return $query->orderByDesc('relevance_score');
    }

    /**
     * Filter by placement zone.
     */
    public function scopeInZone($query, string $zone)
    {
        return $query->where('placement_zone', $zone);
    }

    // ─── Helpers ─────────────────────────────────────────────────

    /**
     * Get a randomly selected anchor text (primary or variation).
     */
    public function getRandomAnchorAttribute(): string
    {
        $variations = $this->anchor_text_variations ?? [];

        if (empty($variations)) {
            return $this->anchor_text_primary;
        }

        $all = array_merge([$this->anchor_text_primary], $variations);
        return $all[array_rand($all)];
    }

    /**
     * Get the source tool's config array.
     */
    public function getSourceToolConfigAttribute(): ?array
    {
        $all = array_merge(config('tools.tools', []), config('pro_calculators', []));
        return $all[$this->source_tool_slug] ?? null;
    }

    /**
     * Get the target tool's config array.
     */
    public function getTargetToolConfigAttribute(): ?array
    {
        $all = array_merge(config('tools.tools', []), config('pro_calculators', []));
        return $all[$this->target_tool_slug] ?? null;
    }
}
